# Generated by Django 4.1 on 2022-11-18 21:14

import cursos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=cursos.models.filePath),
        ),
    ]
