# Generated by Django 4.1 on 2022-10-09 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_alter_categoria_criadoem_alter_modulo_criadoem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descricao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='titulo',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='cursos.categoria', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='titulo',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='video',
            name='linkVideo',
            field=models.CharField(max_length=255, verbose_name='Link do Vídeo'),
        ),
        migrations.AlterField(
            model_name='video',
            name='modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='cursos.modulo', verbose_name='Módulo'),
        ),
        migrations.AlterField(
            model_name='video',
            name='titulo',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
    ]
