# Generated by Django 4.1 on 2022-10-13 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_alter_categoria_descricao_alter_categoria_titulo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.URLField(default='', verbose_name='Link Thumb'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='linkVideo',
            field=models.URLField(verbose_name='Link do Vídeo'),
        ),
    ]
